
<html>
<?php
include("AAA.php");
?>
<body>
<center>
<img src="img2/20160504_061434.jpg" width="500" height="300"></center>
<center><font size="+2" color="#990000">
Awanti High School is built in  year -2003.<br>We provide morning shift and day shift for our students.<br>Timing of morning shift is- 7:30 to 11:30.
<br>
Timing of day shift is- 12 to 4:30.
<br>
Morning shift in include classes from kg1 to 5th.<br>
Day shift in included classes from 6th to 10th.
<br>


</center>
</body>
</html>