<html>
<?php
include("headsimple.php");
?>
<body><br>
<center>
<img src="img2/IMG_20160927_114536.jpg" width="600" height="300"></center>
<center>
<center><font size="+2" color="#990000">
Awanti High School is built in  year -2003.<br>We provide morning shift and day shift for our students.<br>Timing of morning shift is- 7:30 to 11:30.
<br>
Timing of day shift is- 12 to 4:30.
<br>
Morning shift in include classes from kg1 to 5th.
Day shift in included classes from 6th to 10th.

</center>
</body>
</html>